export const INGREDIENTS={rice:{name:'Brown rice',unit:'g',pack:500,cents:240,stock:8,avoids:[]},lentils:{name:'Red lentils',unit:'g',pack:500,cents:280,stock:6,avoids:[]},carrots:{name:'Carrots',unit:'g',pack:500,cents:160,stock:8,avoids:[]},tomatoes:{name:'Chopped tomatoes',unit:'can',pack:1,cents:145,stock:10,avoids:[]},yogurt:{name:'Plain yogurt',unit:'g',pack:400,cents:245,stock:5,avoids:['milk']},chickpeas:{name:'Chickpeas',unit:'can',pack:1,cents:155,stock:10,avoids:[]},coconut:{name:'Coconut milk',unit:'can',pack:1,cents:220,stock:5,avoids:[]},spinach:{name:'Spinach',unit:'g',pack:200,cents:225,stock:4,avoids:[]},pasta:{name:'Pasta',unit:'g',pack:500,cents:180,stock:7,avoids:['wheat']},broccoli:{name:'Broccoli',unit:'g',pack:400,cents:240,stock:5,avoids:[]},milk:{name:'Milk',unit:'ml',pack:1000,cents:240,stock:5,avoids:['milk']},cheese:{name:'Cheddar',unit:'g',pack:200,cents:320,stock:5,avoids:['milk']},peanuts:{name:'Roasted peanuts',unit:'g',pack:200,cents:210,stock:5,avoids:['peanuts']},noodles:{name:'Rice noodles',unit:'g',pack:250,cents:210,stock:7,avoids:[]},peppers:{name:'Bell peppers',unit:'g',pack:400,cents:290,stock:4,avoids:[]}};
export const RECIPES=[
 {id:'lentil',name:'Golden lentil harvest bowls',subtitle:'Warm rice, roasted carrots and tomato lentils',minutes:30,diet:'vegan',image:'bowl',ingredients:{rice:300,lentils:240,carrots:300,tomatoes:1},steps:['Cook the rice according to its package instructions.','Prepare the lentils and tomatoes in a pan while roasting the carrots.','Divide the ingredients into bowls and serve.'],baseServings:4},
 {id:'curry',name:'Coconut chickpea supper',subtitle:'A one-pan curry with spinach and brown rice',minutes:25,diet:'vegan',image:'curry',ingredients:{rice:280,chickpeas:2,coconut:1,spinach:200},steps:['Cook the rice according to its package instructions.','Combine the chickpeas and coconut milk in a pan.','Add spinach, heat through and serve over rice.'],baseServings:4},
 {id:'pasta',name:'Broccoli comfort bake',subtitle:'A generous pasta bake with a golden cheese top',minutes:40,diet:'vegetarian',image:'pasta',ingredients:{pasta:360,broccoli:400,milk:300,cheese:140},steps:['Cook the pasta according to its package instructions.','Prepare broccoli and a milk-and-cheese sauce.','Combine and bake following your usual kitchen procedure.'],baseServings:4},
 {id:'noodles',name:'Peanut & pepper noodles',subtitle:'Bright peppers and rice noodles with peanut crunch',minutes:20,diet:'vegan',image:'noodles',ingredients:{noodles:250,peanuts:80,peppers:300,carrots:160},steps:['Prepare rice noodles according to their package instructions.','Cook sliced peppers and carrots.','Combine with the noodles and peanuts.'],baseServings:4}
];
const day=(date,n)=>{const d=new Date(date);d.setDate(d.getDate()+n);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
export function createWorkspace(now=new Date()){
 return {schemaVersion:1,revision:0,profile:{servings:4,diet:'vegetarian',avoid:['peanuts'],budgetCents:1800},pantry:[{id:'LOT-R',ingredient:'rice',qty:620,expires:day(now,60)},{id:'LOT-L',ingredient:'lentils',qty:310,expires:day(now,40)},{id:'LOT-C',ingredient:'carrots',qty:480,expires:day(now,2)},{id:'LOT-T',ingredient:'tomatoes',qty:1,expires:day(now,100)},{id:'LOT-P',ingredient:'pasta',qty:450,expires:day(now,90)},{id:'LOT-Y',ingredient:'yogurt',qty:160,expires:day(now,1)}],catalog:structuredClone(INGREDIENTS),calendar:[],orders:[],audit:[],memory:[],completed:{}};
}
